/* Each identity is evaluated independently on its two sides. */
(function(root){
  'use strict';
  const M=typeof module!=='undefined'&&module.exports?require('./math.js'):root.VC;
  const {add,sub,scale,dot,cross,grad,div,curl,lap,vlap,directional}=M;
  const sum=v=>v.reduce((a,b)=>typeof a==='number'?a+b:add(a,b));
  const scalar=(a,b)=>p=>a*p[0]**2+b*p[1]**2+0.5*p[0]*p[1]+0.2*p[2]**2;
  const flow=(a,b)=>p=>[a*p[0]-b*p[1],b*p[0]+a*p[1],0];
  const terms=(...items)=>items.map(([label,fn])=>({label,fn}));
  const lessons=[
    {id:'gradient',group:'Start here',title:'Gradient',tag:'A scalar becomes an arrow',formula:'∇f = (∂f/∂x, ∂f/∂y, ∂f/∂z)',types:'scalar → vector',
      intuition:'Imagine f as height. The gradient points towards the steepest increase. Its magnitude is the steepest slope, not the height itself.',
      observe:'Change a or b to turn the bowl into a saddle. Click a point: the arrow should cross the local contour at a right angle. At a stationary point the gradient vanishes even if the height is nonzero.',
      trap:'A gradient is not a path and not a velocity by definition. The arrows are a field of local slopes. The plot shows its x–y components; the readout also includes z.',
      proof:['A small displacement gives Δf ≈ ∇f · Δr.','Along a unit direction u, the slope is ∇f · u.','This is largest when u points along ∇f. A contour has Δf = 0, so its tangent is perpendicular to the gradient.'],
      question:'If you double f everywhere, what happens to its gradient?',answer:'Its gradient doubles. The contour shapes stay the same, but their values and slopes change.',
      build(a,b){const f=scalar(a,b);return {example:'f = a x² + b y² + ½xy + 0.2z²',source:f,sourceType:'scalar',lhs:p=>grad(f,p),rhs:terms(['∇f',p=>grad(f,p)]),background:f,contours:true};}},
    {id:'divergence',group:'Start here',title:'Divergence',tag:'Net outward flow per volume',formula:'∇·F = ∂Fₓ/∂x + ∂Fᵧ/∂y + ∂Fz/∂z',types:'vector → scalar',
      intuition:'Put a tiny box around a point. Divergence asks whether more field flows out than in, divided by the box volume. A fast uniform flow still has zero divergence.',
      observe:'a controls expansion; b controls rotation. Set a = 0 and increase b: the arrows rotate, but there is no net outward flux. The orange square is a finite area probe.',
      trap:'Divergence is not the arrow length. It measures how the field changes across opposite faces. Here Fz = 0 and there is no z dependence, so 3D divergence equals the planar divergence.',
      proof:['Right minus left flux ≈ (∂ₓFₓ) Δx Δy Δz.','Add the other two pairs of faces.','Divide by Δx Δy Δz and take the small-box limit.'],
      question:'Can a field have both divergence and curl?',answer:'Yes. F = (ax − by, bx + ay, 0) has divergence 2a and curl (0,0,2b). Expansion and rotation are independent here.',
      build(a,b){const F=flow(a,b);return {example:'F = (ax − by, bx + ay, 0); div F = 2a',source:F,sourceType:'vector',lhs:p=>div(F,p),rhs:terms(['div F',p=>div(F,p)]),probe:'flux',F};}},
    {id:'curl',group:'Start here',title:'Curl',tag:'Local circulation about an axis',formula:'(∇×F)z = ∂ₓFᵧ − ∂ᵧFₓ',types:'vector → vector',
      intuition:'Curl measures circulation per oriented area in the small-loop limit. In this plane, positive z-curl means counterclockwise circulation when viewed from +z.',
      observe:'Set b = 0 and vary a: expansion has no curl. Set a = 0 and change the sign of b: circulation reverses. A blue dot means towards you (+z); a cross means away (−z).',
      trap:'Curved arrows are not enough to establish nonzero curl. Curl is local, and its direction follows the right-hand rule. For rigid rotation, angular velocity is half the curl.',
      proof:['For a small counterclockwise rectangle, bottom plus top contributions give −∂ᵧFₓ times area.','Right plus left contributions give ∂ₓFᵧ times area.','Their sum is (∇×F)z times area. The other components use other oriented planes.'],
      question:'For F = (−by, bx, 0), is the curl b or 2b?',answer:'It is (0,0,2b). Both velocity gradients contribute. The rigid-body angular velocity is b along z.',
      build(a,b){const F=flow(a,b);return {example:'F = (ax − by, bx + ay, 0); curl F = (0,0,2b)',source:F,sourceType:'vector',lhs:p=>curl(F,p),rhs:terms(['curl F',p=>curl(F,p)]),probe:'circulation',F};}},
    {id:'laplacian',group:'Start here',title:'Laplacian',tag:'Divergence of the uphill arrows',formula:'∇·(∇f) = ∇²f',types:'scalar → vector → scalar',
      intuition:'The Laplacian sums the curvature in each coordinate direction. Positive values mean the local neighbour average exceeds the centre value, in the small-neighbourhood limit.',
      observe:'Change a and b independently. A saddle can have zero Laplacian when positive and negative curvatures cancel. The small z curvature in this example adds 0.4.',
      trap:'Zero Laplacian does not mean flat or constant. For example x² − y² is harmonic but has a nonzero gradient away from the origin.',
      proof:['∇f = (fₓ,fᵧ,fz).','Taking divergence gives fₓₓ + fᵧᵧ + fzz.','That sum is the scalar Laplacian.'],
      question:'What is ∇²(x² − y²)?',answer:'2 − 2 = 0. The two curvatures cancel, even though the surface is a saddle.',
      build(a,b){const f=scalar(a,b);const G=p=>grad(f,p);return {example:'f = a x² + b y² + ½xy + 0.2z²; ∇²f = 2a + 2b + 0.4',source:G,sourceType:'vector',lhs:p=>div(G,p),rhs:terms(['∇²f',p=>lap(f,p)]),background:f,contours:true};}},
    {id:'curl-gradient',group:'The zero identities',title:'Curl of a gradient',tag:'Uphill arrows have no local circulation',formula:'∇×(∇f) = 0',types:'scalar → vector → vector',
      intuition:'A smooth height function cannot keep increasing as you walk around a tiny closed loop and return to your starting point. The local circulation of its gradient cancels.',
      observe:'Make the contours into a saddle. The gradient arrows change substantially, while every component of their curl stays zero (apart from numerical roundoff).',
      trap:'The identity requires continuous second partial derivatives. The reverse statement, curl-free implies a global scalar potential, needs domain conditions too.',
      proof:['The z component is ∂ₓ(fᵧ) − ∂ᵧ(fₓ).','For a C² scalar field, fᵧₓ = fₓᵧ.','The x and y components cancel by the same mixed-partial argument.'],
      question:'Does ∇×∇f = 0 mean ∇f itself is zero?',answer:'No. A nonconstant smooth potential usually has a nonzero gradient. Its curl is zero, not the gradient.',
      build(a,b){const f=scalar(a,b);const G=p=>grad(f,p);return {example:'f = a x² + b y² + ½xy + 0.2z²',source:G,sourceType:'vector',lhs:p=>curl(G,p),rhs:terms(['zero vector',()=>[0,0,0]]),background:f,contours:true};}},
    {id:'divergence-curl',group:'The zero identities',title:'Divergence of a curl',tag:'Curl fields have no local sources',formula:'∇·(∇×A) = 0',types:'vector → vector → scalar',
      intuition:'Flux generated by a smooth curl has no net source. Contributions cancel through paired mixed partial derivatives. This is a local differential statement.',
      observe:'Here the x–y projection can appear to expand. Move the z slice and inspect the full vector: the z derivative balances the planar divergence. A 2D picture alone can be misleading.',
      trap:'Do not calculate only ∂ₓFₓ + ∂ᵧFᵧ for a 3D field. The missing ∂zFz can be exactly the term that cancels the apparent source.',
      proof:['Expand the six terms: ∂ₓ∂ᵧAz − ∂ₓ∂zAᵧ + ∂ᵧ∂zAₓ − ∂ᵧ∂ₓAz + ∂z∂ₓAᵧ − ∂z∂ᵧAₓ.','Pair equal mixed partials with opposite signs.','Every term cancels for a C² field.'],
      question:'Can the x–y projection of a divergence-free field look like a source?',answer:'Yes. Its planar divergence can be balanced by variation of the out-of-plane component with z.',
      build(a,b){const A=p=>[a*p[1]*p[2],b*p[0]*p[2],p[0]*p[1]];const C=p=>curl(A,p);return {example:'A = (ayz, bxz, xy); curl A = ((1−b)x, (a−1)y, (b−a)z)',source:C,sourceType:'vector',lhs:p=>div(C,p),rhs:terms(['zero scalar',()=>0])};}},
    {id:'curl-curl',group:'Second derivatives',title:'Curl of a curl',tag:'Two different second-derivative effects',formula:'∇×(∇×F) = ∇(∇·F) − ∇²F',types:'vector → vector',
      intuition:'The double curl is not generally zero. It combines variation of the source strength with a subtraction of the componentwise curvature of the field.',
      observe:'Toggle the two right-hand terms. At a = 2b they cancel in this example; away from that setting the double curl points along y.',
      trap:'∇²F means apply the scalar Laplacian to each Cartesian component. If div F = 0, double curl equals −∇²F, not zero in general.',
      proof:['The x component expands to ∂ₓ∂ᵧFᵧ + ∂ₓ∂zFz − ∂ᵧ²Fₓ − ∂z²Fₓ.','Add and subtract ∂ₓ²Fₓ.','Group as ∂ₓ(div F) − ∇²Fₓ; repeat for y and z.'],
      question:'If div F = 0, does curl curl F vanish?',answer:'Only if ∇²F also vanishes. In general curl curl F = −∇²F for a divergence-free field.',
      build(a,b){const F=p=>[a*p[0]*p[1],b*p[0]**2,0];return {example:'F = (axy, bx², 0); double curl = (0,a−2b,0)',source:F,sourceType:'vector',lhs:p=>curl(q=>curl(F,q),p),rhs:terms(['∇(div F)',p=>grad(q=>div(F,q),p)],['−∇²F',p=>scale(vlap(F,p),-1)])};}},
    {id:'grad-product',group:'Product rules',title:'Gradient of a product',tag:'Two ways the product can change',formula:'∇(fg) = f∇g + g∇f',types:'scalar × scalar → vector',
      intuition:'When you move, fg changes because g changes and because f changes. Each contribution is weighted by the value of the other factor.',
      observe:'Turn off either contribution on the right. You will usually lose agreement. Click different points: a term can vanish locally without vanishing everywhere.',
      trap:'∇ is a differential operator, so it acts on both factors. You cannot treat it as an ordinary vector and distribute without the product rule.',
      proof:['For each coordinate i, ∂ᵢ(fg) = f∂ᵢg + g∂ᵢf.','Put the three component equations into one vector.','The result is f∇g + g∇f.'],
      question:'Why are there two terms rather than just f∇g?',answer:'Because f may change with position too. The g∇f term measures that additional change.',
      build(a,b){const f=p=>p[0]+a*p[1],g=p=>Math.cos(b*p[0])+p[1]**2+0.1*p[2];const fg=p=>f(p)*g(p);return {example:'f = x+ay; g = cos(bx)+y²+0.1z',source:fg,sourceType:'scalar',background:fg,lhs:p=>grad(fg,p),rhs:terms(['f∇g',p=>scale(grad(g,p),f(p))],['g∇f',p=>scale(grad(f,p),g(p))])};}},
    {id:'div-product',group:'Product rules',title:'Divergence of a scaled field',tag:'The weighting can create sources',formula:'∇·(fA) = f(∇·A) + (∇f)·A',types:'scalar × vector → scalar',
      intuition:'Scaling a field by a spatially varying f changes its flux balance in two ways: the original sources are weighted, and the weighting changes along the arrows.',
      observe:'At a = 0, f is constant and the second term disappears. Increase a: the spatially changing weight makes a new contribution.',
      trap:'A divergence-free A does not imply fA is divergence-free. The directional change of f along A can still create net flux.',
      proof:['Expand ∑ᵢ ∂ᵢ(fAᵢ).','Apply the ordinary product rule: ∑ᵢ f∂ᵢAᵢ + ∑ᵢ Aᵢ∂ᵢf.','Recognise f div A + ∇f · A.'],
      question:'When does a divergence-free field remain divergence-free after scaling?',answer:'When A · ∇f = 0, so f does not change along the field direction.',
      build(a,b){const f=p=>1+a*p[0],A=flow(1,b),F=p=>scale(A(p),f(p));return {example:'f = 1+ax; A = (x−by, bx+y, 0)',source:F,sourceType:'vector',lhs:p=>div(F,p),rhs:terms(['f div A',p=>f(p)*div(A,p)],['∇f · A',p=>dot(grad(f,p),A(p))])};}},
    {id:'curl-product',group:'Product rules',title:'Curl of a scaled field',tag:'Uneven weighting creates shear',formula:'∇×(fA) = f(∇×A) + (∇f)×A',types:'scalar × vector → vector',
      intuition:'The original circulation is weighted by f. A gradient of the weight across the flow also contributes circulation, through ∇f × A.',
      observe:'Set b = 0: the original A has no curl, but weighting it unevenly can produce curl. Toggle each term and follow the dot/cross symbols.',
      trap:'Cross-product order matters: ∇f × A is the negative of A × ∇f. This is a common sign mistake.',
      proof:['The z component is ∂ₓ(fAᵧ) − ∂ᵧ(fAₓ).','Expand: f(∂ₓAᵧ − ∂ᵧAₓ) + fₓAᵧ − fᵧAₓ.','Recognise f(curl A)z + (∇f × A)z.'],
      question:'Can multiplying a curl-free field by f introduce curl?',answer:'Yes, when ∇f × A is nonzero. A weight gradient across the flow introduces local shear.',
      build(a,b){const f=p=>1+a*p[0],A=flow(1,b),F=p=>scale(A(p),f(p));return {example:'f = 1+ax; A = (x−by, bx+y, 0)',source:F,sourceType:'vector',lhs:p=>curl(F,p),rhs:terms(['f curl A',p=>scale(curl(A,p),f(p))],['∇f × A',p=>cross(grad(f,p),A(p))])};}},
    {id:'div-cross',group:'Product rules',title:'Divergence of a cross product',tag:'A dot-with-curl difference',formula:'∇·(A×B) = B·(∇×A) − A·(∇×B)',types:'vector × vector → scalar',
      intuition:'The cross product builds a perpendicular field. Its sources are controlled by how A and B turn, projected onto the other field.',
      observe:'Toggle B · curl A and −A · curl B separately. The minus sign is essential. At a = 0 the first term vanishes but the second can remain.',
      trap:'A and B are not interchangeable here. Swapping them changes A×B to −A×B and reverses the entire identity.',
      proof:['Expand A×B into components, then take divergence.','Collect derivatives of A into B · curl A.','Collect derivatives of B into −A · curl B.'],
      question:'What changes if A and B are swapped?',answer:'Both sides reverse sign, because the cross product is antisymmetric.',
      build(a,b){const A=p=>[0,0,1+a*p[0]*p[1]],B=flow(1,b),F=p=>cross(A(p),B(p));return {example:'A = (0,0,1+axy); B = (x−by, bx+y, 0)',source:F,sourceType:'vector',lhs:p=>div(F,p),rhs:terms(['B · curl A',p=>dot(B(p),curl(A,p))],['−A · curl B',p=>-dot(A(p),curl(B,p))])};}},
    {id:'curl-cross',group:'Product rules',title:'Curl of a cross product',tag:'Four terms, two kinds of change',formula:'∇×(A×B) = A(∇·B) − B(∇·A) + (B·∇)A − (A·∇)B',types:'vector × vector → vector',
      intuition:'Two terms describe source strengths, and two describe how one field changes as you move along the other. Keep these pairs separate in your mind.',
      observe:'Switch off terms one by one. Change the z slice: the in-plane arrows do not contain the whole 3D story.',
      trap:'(B·∇)A is a directional derivative of A, not B times div A. Its i component is Bₓ∂ₓAᵢ + Bᵧ∂ᵧAᵢ + Bz∂zAᵢ.',
      proof:['Use (A×B)ᵢ = εᵢⱼₖ AⱼBₖ and contract the two Levi-Civita symbols.','The component result is ∂ⱼ(AᵢBⱼ − AⱼBᵢ).','Apply the product rule to those two products to obtain the four terms.'],
      question:'What does (B·∇)A mean geometrically?',answer:'Move a small distance in direction B and measure how every component of A changes. It is a vector.',
      build(a,b){const A=p=>[a*p[1],p[0],p[2]],B=p=>[p[0],b*p[2],p[1]],F=p=>cross(A(p),B(p));return {example:'A = (ay,x,z); B = (x,bz,y)',source:F,sourceType:'vector',lhs:p=>curl(F,p),rhs:terms(['A div B',p=>scale(A(p),div(B,p))],['−B div A',p=>scale(B(p),-div(A,p))],['(B·∇)A',p=>directional(B,A,p)],['−(A·∇)B',p=>scale(directional(A,B,p),-1)])};}},
    {id:'grad-dot',group:'Product rules',title:'Gradient of a dot product',tag:'Directional changes plus turning',formula:'∇(A·B) = (A·∇)B + (B·∇)A + A×(∇×B) + B×(∇×A)',types:'vector · vector → scalar → vector',
      intuition:'The dot product measures alignment and magnitude together. Its spatial gradient involves directional changes plus the curls needed to account for turning.',
      observe:'Change a: it changes curl A. In this example curl B is zero, so one term is always zero. The other three still reconstruct the full gradient.',
      trap:'This is not just two directional derivatives. Those alone generally miss the curl terms.',
      proof:['Differentiate AⱼBⱼ with respect to coordinate i.','Rewrite Aⱼ∂ᵢBⱼ as Aⱼ∂ⱼBᵢ + [A×curl B]ᵢ.','Do the same for the derivative of A to get all four terms.'],
      question:'When do the two cross-with-curl terms disappear?',answer:'When both A and B are curl-free, though individual cross terms can also vanish for other reasons such as parallel vectors.',
      build(a,b){const A=p=>[a*p[1],p[0],0],B=p=>[p[0],b*p[1],0],f=p=>dot(A(p),B(p));return {example:'A = (ay,x,0); B = (x,by,0); A·B = (a+b)xy',source:f,sourceType:'scalar',background:f,lhs:p=>grad(f,p),rhs:terms(['(A·∇)B',p=>directional(A,B,p)],['(B·∇)A',p=>directional(B,A,p)],['A × curl B',p=>cross(A(p),curl(B,p))],['B × curl A',p=>cross(B(p),curl(A,p))])};}},
    {id:'flux-theorem',group:'Local to global',title:'Divergence theorem',tag:'Interior sources equal boundary flux',formula:'∯∂V F·n dS = ∭V ∇·F dV',types:'boundary integral = volume integral',
      intuition:'Divide a region into tiny boxes. Flux on shared interior faces cancels, leaving only the outer boundary. The sum of the local source strengths equals outward flux.',
      observe:'This is the planar analogue on a square. Resize the square: total flux scales with its area. Change b: rotation contributes no net outward flux.',
      trap:'Use a closed boundary and outward normals. This demo displays the 2D theorem; it is also a unit-height prism example because F has no z component or dependence.',
      proof:['Each small box has outward flux ≈ divergence × its volume.','Adjacent boxes have opposite normals on a shared face. Their internal fluxes cancel.','Only the external faces survive when all boxes are added.'],
      question:'If the square is twice as wide, how does total flux change here?',answer:'It becomes four times as large, because the divergence is uniform and the planar area quadruples.',
      build(a,b){const F=flow(a,b);return {example:'F = (ax−by, bx+ay, 0); square side 2r; flux = 8ar²',source:F,sourceType:'vector',lhs:p=>div(F,p),rhs:terms(['div F',p=>div(F,p)]),probe:'flux',F};}},
    {id:'stokes',group:'Local to global',title:'Stokes’ theorem',tag:'Interior curl equals edge circulation',formula:'∮∂S F·dr = ∬S (∇×F)·n dS',types:'boundary integral = surface integral',
      intuition:'Tile a surface with tiny loops. Shared edges are traversed in opposite directions and cancel. Only the outside edge remains.',
      observe:'Resize the counterclockwise square. Circulation grows with area here. Change a: expansion contributes no circulation. The normal is +z.',
      trap:'Boundary orientation and surface normal must agree by the right-hand rule. Smoothness must hold on a neighbourhood of the entire spanning surface.',
      proof:['Each small loop has circulation ≈ normal curl × its area.','Shared edges cancel when the loops are summed.','The remaining outer loop has the same circulation as the integral of curl over the surface.'],
      question:'Why can’t you apply the ordinary disk version to the singular vortex in the next lesson?',answer:'The vortex is undefined at the origin, so it is not smooth on the entire disk spanning the loop.',
      build(a,b){const F=flow(a,b);return {example:'F = (ax−by, bx+ay, 0); square side 2r; circulation = 8br²',source:F,sourceType:'vector',lhs:p=>curl(F,p),rhs:terms(['curl F',p=>curl(F,p)]),probe:'circulation',F};}},
    {id:'vortex',group:'Local to global',title:'The hole in the domain',tag:'Curl-free is a local statement',formula:'curl F = 0 away from 0; ∮ F·dr = 2πb around 0',types:'local derivatives ≠ global topology',
      intuition:'A field can turn around a missing point while having zero curl wherever it is defined. A loop around the hole cannot be shrunk to a point inside the domain.',
      observe:'Increase b: circulation around the origin increases, while the local curl away from the hole stays zero. The shaded disk is excluded from sampling; the true singularity is the origin.',
      trap:'No contradiction: the field fails to be smooth at the origin, so Stokes’ theorem cannot use a disk that includes it. A simply connected domain is a sufficient condition for a smooth curl-free field to have a global potential.',
      proof:['For F = b(−y,x,0)/(x²+y²), direct differentiation gives zero curl at r > 0.','On a circle of radius R, F = (b/R)eθ and dr = R eθ dθ.','The circulation is ∫₀²π b dθ = 2πb, independent of R.'],
      question:'Does zero curl everywhere in a punctured plane guarantee path independence?',answer:'No. Loops that wind around the missing origin have nonzero circulation.',
      build(a,b){const F=p=>{const r=p[0]**2+p[1]**2;return [-b*p[1]/r,b*p[0]/r,0];};return {example:'F = b(−y,x,0)/(x²+y²), x²+y² > 0; a is unused',source:F,sourceType:'vector',lhs:p=>curl(F,p),rhs:terms(['zero away from origin',()=>[0,0,0]]),singular:true,probe:'vortex',F};}}
  ];
  const api={lessons,sum,flow};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Lab=api;
})(typeof window==='undefined'?globalThis:window);
